version: '1.0'
stages:
  - checkout
  - prepare   
  - deploy
  - destroy
steps:
  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'rajivsh85/testcf'
    revision: master
    git: github      
  SetupAuth:
    image: alpine:3.9
    title: Setting up Google cloud auth
    stage: prepare
    commands:
      - echo $ACCOUNT_JSON_CONTENT > /codefresh/volume/account.json
      - cf_export GOOGLE_CLOUD_KEYFILE_JSON=/codefresh/volume/account.json
  DeployWithTerraform:
    image: hashicorp/terraform:0.12.0
    title: Deploying blah blah
    stage: deploy
    commands:
      - terraform init
      - terraform apply -auto-approve
  generate_destroy_plan:
    title: Generate Plan
    stage: destroy

    commands:
      - terraform version
      - terraform init
      - terraform plan -input=false -lock=false -destroy

  approve_destroy:
    type: pending-approval
    stage: destroy
    title: Approve Destroy
    timeout:
      duration: 48
      finalState: denied

  destroy:
    title: Do Destroy
    stage: destroy
    commands:
      - terraform version
      - terraform init
      - terraform destroy -input=false -auto-approve